const token = '1480815536:AAFJO5Tn05vST4Kdt5GQUgqbahHJvsnUqsc',
      chatId = '-1001211332831';

let userNotifications = [],
    itemsList = [],
    savedList = [],
    deviceInfo = '',
    activetab = '',
    selectedRows = 0,
    selectedItems = 0,
    placeSwitch = 'assignList',
    assignListId = '',
    useListId = '',
    delItemId = '';

// multilang support (0 == 'ru', 1 == 'en')
let defaultLang = 0,
    translations = [ 
        ['Список покупок',
        '<code>1 - составляйте списки покупок<br><br>2 - отмечайте покупки в своём списке<br><br>3 - сохраняйте избранные списки<br><br>4 - устанавливайте напоминания</code>',
        'Перейти к покупкам',
        'Помогите нам стать лучше',
        'Вы можете помочь нам сделать приложение лучше, отправив свои сохраненные списки покупок. Полученная информация поможет нам сделать приложение удобнее для использования. Вся передаваемая вами информация деперсонализированна мы получим только ваши списки покупок, без привязки к вашим персональным данным.',
        'Отправить',
        'Не отправлять',
        'Сервис для составления списка покупок',
        'Закончить покупки',
        'Напоминания',
        'Редактировать список',
        'Наименование',
        'Кол-во',
        'Сохранить список в избранное',
        'Купить по списку',
        'Сохраненные списки',
        'Отмена',
        'Завершить',
        'Текущий прогресс будет утерян',
        'В список покупок',
        'Добавить',
        'Отмена',
        'Удалить список',
        'Удалить',
        'Список также будет удалён из напоминаний',
        'Сохранить список',
        'Название',
        'Сохранить',
        'Добавить напоминание',
        'Комментарий',
        'Загрузить список',
        'Загрузить',
        'Текущий список покупок будет изменён',
        'Основные показатели',
        'Заполните все поля',
        'Copyright © 2020 Andranik Sarkisyan',
        'шт', 'кг', 'г', 'л', 'мл',
        'Список покупок', 'Позиции', 'План', 'Факт'],
        ['Shopping list',
        '<code>1 - make shopping lists<br><br>2 - mark your purchases in the list<br><br>3 - save your favorite lists<br><br>4 - set reminders</code>',
        'Go to shopping',
        'Help us become better',
        'You can help us make the app better by submitting your saved shopping lists. The information received will help us make the application more convenient to use. All information you transmit is depersonalized, we will only receive your shopping lists, without being linked to your personal data.',
        'Send',
        'Do not send',
        'Service for compiling a shopping list',
        'Finish shopping',
        'Notifications',
        'Edit list',
        'Name',
        'Qty',
        'Save the list to favorites',
        'Buy from the list',
        'Saved lists',
        'Cancel',
        'Complete',
        'Current progress will be lost',
        'Add to shopping list',
        'Add',
        'Cancel',
        'Delete list',
        'Delete',
        'The list will also be removed from notifications',
        'Save List',
        'Name',
        'Save',
        'Add notification',
        'Comment',
        'Load',
        'Load',
        'The current shopping list will be changed',
        'Basic indicators',
        'Please fill all fields',
        'Copyright © 2020 Andranik Sarkisyan',
        'pc.', 'kg', 'g', 'l', 'ml',
        'Shopping list', 'Items', 'Planned', 'Purchased']
    ];

// empty html forms init
let init_data,
    send_data_warn,
    nav_main,
    nav_main_notifications,
    nav_admin,
    nav_admin_save,
    nav_user,
    nav_topList,
    nav_topList_inactive_assign,
    warn_popup,
    add_item_popup,
    del_item_popup,
    save_list_popup,
    assign_list_popup,
    use_list_popup,
    chart_add,
    exit_button,
    empty_table,
    inbutton_loader,
    cm_spinner,
    popup_error,
    selectedLang;

// check selected lang
if (localStorage.selectedLang) {
    selectedLang = localStorage.selectedLang;
}
else {
    selectedLang = 'ru';
}